
# This file is automatically generated, you probably don't want to edit this

.jmvrefs <- list(
    `lavaan`=list(
        `type`="article", 
        `author`="Rosseel, Y.", 
        `year`=2012, 
        `title`="lavaan: An R Package for Structural Equation Modeling", 
        `publisher`="Journal of Statistical Software", 
        `volume`=48, 
        `issue`=2, 
        `pages`="1-36", 
        `url`="https://doi.org/10.18637/jss.v048.i02"), 
    `lavaanPkg`=list(
        `type`="software", 
        `author`="Rosseel, Y., Jorgensen, T. D., & Rockwood, N.", 
        `year`=2025, 
        `title`="lavaan: Latent Variable Analysis", 
        `publisher`="[R package]. Retrieved from https://cran.r-project.org/package=lavaan", 
        `url`="https://cran.r-project.org/package=lavaan"))
